## Explication data et dictionnaire

<b>Data</b> -> la quantité d'ingrédient en grammes pour 1kg de produit

<b>Poids_unite</b> -> combien de grammes pour 1 produit

<b>df_unite</b> -> quantité d'ingrédient en kg pour chaque produit

<b>prix_ingredients</b> -> prix au kg de chaque ingrédient

---

L'eau qui fait partie de la recette de chaque produit n'a pas été pris en compte.

In [67]:
import pandas as pd

In [68]:
data = {
    "BAGUETTE": {"farine": 640, "sel": 18, "levure": 2},
    "TRADITIONAL_BAGUETTE": {"farine": 640, "sel": 18, "levure": 2},
    "PAIN_AU_CHOCOLAT": {"farine": 450, "sel": 10, "levure": 20, "sucre": 60, "beurre": 220, "lait": 20, "barres_chocolat": 20},
    "CROISSANT": {"farine": 470, "sel": 10, "levure": 20, "sucre": 50, "beurre": 220, "lait": 20},
    "BANETTE": {"farine": 630, "sel": 18, "levure": 2},
    "SPECIAL_BREAD": {"farine": 550, "sel": 18, "levure": 2, "graines": 70},
    "CAMPAGNE": {"farine": 500, "farine_de_seigle": 150, "sel": 20, "levure": 10},
    "CEREAL_BAGUETTE": {"farine": 600, "sel": 18, "levure": 2, "graines": 60},
    "VIK_BREAD": {"farine": 400, "farine_de_seigle": 200, "sel": 18, "levure": 5, "son_de_ble": 7},
    "ECLAIR": {"farine": 300, "beurre": 200, "sucre": 40, "sel": 10, "creme": 300, "oeufs": 150},
    "COOKIE": {"farine": 550, "sel": 5, "sucre": 300, "beurre": 300, "oeufs": 100, "chocolat": 200},
    "BOULE_400G": {"farine": 650, "sel": 18, "levure": 2},
    "TARTELETTE": {"farine": 500, "sucre": 200, "beurre": 250, "oeufs": 150, "creme": 200, "sel": 5},
}

df = pd.DataFrame.from_dict(data, orient="index").fillna(0)

poids_unite = {
    "BAGUETTE": 0.25,
    "TRADITIONAL_BAGUETTE": 0.25,
    "PAIN_AU_CHOCOLAT": 0.08,
    "CROISSANT": 0.07,
    "BANETTE": 0.25,
    "SPECIAL_BREAD": 0.50,
    "CAMPAGNE": 0.50,
    "CEREAL_BAGUETTE": 0.25,
    "VIK_BREAD": 0.50,
    "ECLAIR": 0.10,
    "COOKIE": 0.05,
    "BOULE_400G": 0.40,
    "TARTELETTE": 0.12,
}

df_unite = df.mul(pd.Series(poids_unite), axis=0) / 1000

prix_ingredients = {
    "farine": 1.2,
    "farine_de_seigle": 1.4,
    "sel": 0.20,
    "levure": 6.0,
    "sucre": 1.0,
    "beurre": 8.0,
    "lait": 0.9,
    "barres_chocolat": 6.5,
    "ameliorants": 4.0,
    "graines_speciales": 3.5,
    "son_de_ble": 1.0,
    "chocolat": 6.0,
    "oeufs": 2.5,
    "creme": 3.0,
}

df_prix = pd.DataFrame.from_dict(prix_ingredients, orient="index", columns=["prix_kg"])

In [69]:
df_unite

,farine,sel,levure,sucre,beurre,lait,barres_chocolat,graines,farine_de_seigle,son_de_ble,creme,oeufs,chocolat
BAGUETTE,0.1600,0.00450,0.0005,0.0000,0.0000,0.0000,0.0000,0.000,0.000,0.0000,0.000,0.000,0.00
TRADITIONAL_BAGUETTE,0.1600,0.00450,0.0005,0.0000,0.0000,0.0000,0.0000,0.000,0.000,0.0000,0.000,0.000,0.00
PAIN_AU_CHOCOLAT,0.0360,0.00080,0.0016,0.0048,0.0176,0.0016,0.0016,0.000,0.000,0.0000,0.000,0.000,0.00
CROISSANT,0.0329,0.00070,0.0014,0.0035,0.0154,0.0014,0.0000,0.000,0.000,0.0000,0.000,0.000,0.00
BANETTE,0.1575,0.00450,0.0005,0.0000,0.0000,0.0000,0.0000,0.000,0.000,0.0000,0.000,0.000,0.00
SPECIAL_BREAD,0.2750,0.00900,0.0010,0.0000,0.0000,0.0000,0.0000,0.035,0.000,0.0000,0.000,0.000,0.00
CAMPAGNE,0.2500,0.01000,0.0050,0.0000,0.0000,0.0000,0.0000,0.000,0.075,0.0000,0.000,0.000,0.00
CEREAL_BAGUETTE,0.1500,0.00450,0.0005,0.0000,0.0000,0.0000,0.0000,0.015,0.000,0.0000,0.000,0.000,0.00
VIK_BREAD,0.2000,0.00900,0.0025,0.0000,0.0000,0.0000,0.0000,0.000,0.100,0.0035,0.000,0.000,0.00
ECLAIR,0.0300,0.00100,0.0000,0.0040,0.0200,0.0000,0.0000,0.000,0.000,0.0000,0.030,0.015,0.00
COOKIE,0.0275,0.00025,0.0000,0.0150,0.0150,0.0000,0.0000,0.000,0.000,0.0000,0.000,0.005,0.01
BOULE_400G,0.2600,0.00720,0.0008,0.0000,0.0000,0.0000,0.0000,0.000,0.000,0.0000,0.000,0.000,0.00
TARTELETTE,0.0600,0.00060,0.0000,0.0240,0.0300,0.0000,0.0000,0.000,0.000,0.0000,0.024,0.018,0.00

In [70]:
df_prix

                   prix_kg
farine                 1.2
farine_de_seigle       1.4
sel                    0.2
levure                 6.0
sucre                  1.0
beurre                 8.0
lait                   0.9
barres_chocolat        6.5
ameliorants            4.0
graines_speciales      3.5
son_de_ble             1.0
chocolat               6.0
oeufs                  2.5
creme                  3.0

In [71]:
df_unite.reset_index().rename(columns={"index": "produit"}).to_csv("data_tmp/ingredients_per_unite.csv", index=False)
df_prix.reset_index().rename(columns={"index": "ingredient"}).to_csv("data_tmp/prix_ingredients.csv", index=False)

In [72]:
test = pd.read_csv("data_tmp/prix_ingredients.csv")
test2 = pd.read_csv("data_tmp/ingredients_per_unite.csv")

test2

,produit,farine,sel,levure,sucre,beurre,lait,barres_chocolat,graines,farine_de_seigle,son_de_ble,creme,oeufs,chocolat
0,BAGUETTE,0.1600,0.00450,0.0005,0.0000,0.0000,0.0000,0.0000,0.000,0.000,0.0000,0.000,0.000,0.00
1,TRADITIONAL_BAGUETTE,0.1600,0.00450,0.0005,0.0000,0.0000,0.0000,0.0000,0.000,0.000,0.0000,0.000,0.000,0.00
2,PAIN_AU_CHOCOLAT,0.0360,0.00080,0.0016,0.0048,0.0176,0.0016,0.0016,0.000,0.000,0.0000,0.000,0.000,0.00
3,CROISSANT,0.0329,0.00070,0.0014,0.0035,0.0154,0.0014,0.0000,0.000,0.000,0.0000,0.000,0.000,0.00
4,BANETTE,0.1575,0.00450,0.0005,0.0000,0.0000,0.0000,0.0000,0.000,0.000,0.0000,0.000,0.000,0.00
5,SPECIAL_BREAD,0.2750,0.00900,0.0010,0.0000,0.0000,0.0000,0.0000,0.035,0.000,0.0000,0.000,0.000,0.00
6,CAMPAGNE,0.2500,0.01000,0.0050,0.0000,0.0000,0.0000,0.0000,0.000,0.075,0.0000,0.000,0.000,0.00
7,CEREAL_BAGUETTE,0.1500,0.00450,0.0005,0.0000,0.0000,0.0000,0.0000,0.015,0.000,0.0000,0.000,0.000,0.00
8,VIK_BREAD,0.2000,0.00900,0.0025,0.0000,0.0000,0.0000,0.0000,0.000,0.100,0.0035,0.000,0.000,0.00
9,ECLAIR,0.0300,0.00100,0.0000,0.0040,0.0200,0.0000,0.0000,0.000,0.000,0.0000,0.030,0.015,0.00
10,COOKIE,0.0275,0.00025,0.0000,0.0150,0.0150,0.0000,0.0000,0.000,0.000,0.0000,0.000,0.005,0.01
11,BOULE_400G,0.2600,0.00720,0.0008,0.0000,0.0000,0.0000,0.0000,0.000,0.000,0.0000,0.000,0.000,0.00
12,TARTELETTE,0.0600,0.00060,0.0000,0.0240,0.0300,0.0000,0.0000,0.000,0.000,0.0000,0.024,0.018,0.00